# fly.toml — IELTS Bot (long-polling + health check)

app            = "ieltsbot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

# ── Runtime process ──────────────────────────────────────────
[processes]
  app = "python main.py"

# ── Service & health-check on :8080 ──────────────────────────
[[services]]
  internal_port = 8080          # matches _start_health_server()
  protocol      = "tcp"
  processes     = ["app"]

  # ── Public endpoints ───────────────────────────────────────
  [[services.ports]]
    handlers = ["http"]         # :80  → HTTP
    port     = 80

  [[services.ports]]
    handlers = ["tls", "http"]  # :443 → HTTPS (auto-TLS)
    port     = 443

  # ── Health check (same port) ───────────────────────────────
  [[services.http_checks]]
    path         = "/ping"
    method       = "get"
    protocol     = "http"
    grace_period = "10s"
    interval     = "15s"
    timeout      = "2s"

# ── VM sizing ────────────────────────────────────────────────
[[vm]]
  cpus     = 1
  memory   = "512mb"
  cpu_kind = "shared"
