# fly.toml — IELTS Bot (long-polling + health check)

app            = "ieltsbot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

# ── Runtime process ──────────────────────────────────────────
[processes]
  app = "python main.py"

# ── Private health-check service on :8080 ───────────────────
[[services]]
  internal_port = 8080          # matches _start_health_server()
  protocol      = "tcp"
  processes     = ["app"]

  # keep the port private (no handlers → not routed to the Internet)
  [[services.ports]]
    handlers = []
    port     = 8080             # advertise the same port we listen on

  [[services.http_checks]]
    path         = "/ping"
    method       = "get"
    protocol     = "http"
    grace_period = "10s"
    interval     = "15s"
    timeout      = "2s"

# ── VM sizing ────────────────────────────────────────────────
[[vm]]
  cpus     = 1
  memory   = "256mb"
  cpu_kind = "shared"
