# fly.toml — IELTS Bot (long-polling + health check)

app            = "ieltsbot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

# ── Runtime process ──────────────────────────────────────────
[processes]
  app = "python main.py"

# ── Health-check service on :8080 ────────────────────────────
[[services]]
  internal_port = 8080
  protocol      = "tcp"
  processes     = ["app"]        # ← links this service to the “app” proc

  # NO public exposure: empty handlers disables routing
  [[services.ports]]
    handlers = []                # keep port private
    port     = 80                # dummy (required by validator)

  [[services.http_checks]]
    path         = "/ping"
    method       = "get"
    protocol     = "http"
    grace_period = "10s"
    interval     = "15s"
    timeout      = "2s"

# ── VM sizing ────────────────────────────────────────────────
[[vm]]
  cpus     = 1
  memory   = "256mb"
  cpu_kind = "shared"
