# fly.toml — IELTS Bot (long-polling + health check)
# Reference: https://fly.io/docs/reference/configuration/

app            = "ieltsbot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"              # adjust if Dockerfile lives elsewhere

# ── Runtime ────────────────────────────────────────────────────
[processes]
  app = "python main.py"                 # long-polling bot entrypoint

# ── Health check (exposes :8080/ping) ─────────────────────────
[[services]]
  internal_port = 8080
  protocol      = "tcp"

  [[services.http_checks]]
    path         = "/ping"
    method       = "get"
    protocol     = "http"
    grace_period = "10s"
    interval     = "15s"
    timeout      = "2s"

# ── VM sizing ─────────────────────────────────────────────────
[[vm]]
  cpus     = 1          # shared-cpu-1x (free tier)
  memory   = "256mb"
  cpu_kind = "shared"
