ALTER TABLE users ADD COLUMN IF NOT EXISTS plan          TEXT DEFAULT 'free';
ALTER TABLE users ADD COLUMN IF NOT EXISTS credits_left  INT  DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activated_at  TIMESTAMPTZ;
